### ISSUE TITLE
Better support for fuzzing Go, remaining - code coverage

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2714]
As of today, ClusterFuzz supports fuzzing Go in the `gofuzz_libfuzzer` mode: https://github.com/dvyukov/go-fuzz#libfuzzer-support

But it's not really convenient to integrate a new Golang project. I think we should do the following:

1) Upgrade the base-builder image to include a recent version of Go toolchain and go-fuzz, so that it was possible to run `go` and `go-fuzz-build` commands from `build.sh` without any problems.

2) Document it :)

### Action items

* [x] Remove `go-fuzz-build` and build fuzz targets using the standard toolchain (available since Go 1.14, we're already on 1.14.2, as we always install the latest stable version).
* [x] (won't fix, see https://github.com/google/oss-fuzz/issues/2714#issuecomment-614387444) Unify the build command (will likely need some wrapper to be included in the base-builder image), migrate all existing projects to the new build interface (instead of using a copy pasted bash function in all build.sh files).
* [x] Update documentation to reflect the new preferred way of building fuzz targets (https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang).
* [x] Update `srcmap` script to work with Go deps (https://github.com/google/oss-fuzz/issues/3355).
* [x] When we get more projects integrated (maybe 30-50), add support for code coverage (https://github.com/google/oss-fuzz/issues/2817).

**Comment by catenacyber** [comment]
I am not sure if it fits here, but I would like to see "LAST TESTED REVISION" on oss-fuzz.com for golang projects 
The trick is, I think, that build.sh uses `go get` instead of `git clone`
Example : https://oss-fuzz.com/testcase-detail/5453012747419648

**Comment by Dor1s** [comment]
Interesting! I guess you meant Dockerfile using `go get`, e.g. https://github.com/google/oss-fuzz/blob/e82397baf623b69e17f29115817c5415f52df32b/projects/gonids/Dockerfile#L19

Yeah, looks like our srcmap script should grab revisions from the repos isntalled via `go get` as well. I'll upload a patch, thanks for noticing this!

**Comment by catenacyber** [comment]
Exactly

Thanks @Dor1s for patching, I did not know where to look, or I would have proposed a patch myself ;-)

**Comment by inferno-chromium** [comment]
Tracking items:
1. Switch to native go instrumentation.
2. Make projects use the native go binary for building.
3. Fix documentation - https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang
4. Add how to write fuzz targets (examples). this section has none - https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/#go-fuzz-support

fyi - @lukasz-milewski @mdempsky

**Comment by Dor1s** [comment]
Thanks @inferno-chromium, I've updated the issue description with more of these.

Also added code coverage (https://github.com/google/oss-fuzz/issues/2817) and srcmap support (https://github.com/google/oss-fuzz/issues/3355).

Regarding

> 4. Add how to write fuzz targets (examples). this section has none - https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/#go-fuzz-support

I'm not sure this would belong to OSS-Fuzz repo, as OSS-Fuzz docs focus on using OSS-Fuzz and do not cover how to write fuzz targets in general (e.g. https://google.github.io/oss-fuzz/getting-started/new-project-guide/ also doesn't have any C/C++ examples).

https://github.com/google/fuzzing might be a better place, or we can point to https://godoc.org/github.com/google/gofuzz

**Comment by Dor1s** [comment]
@inferno-chromium thanks a ton for adding the new instrumentation support (https://github.com/google/oss-fuzz/pull/3633) and migrating all Go projects to use it (https://github.com/google/oss-fuzz/pull/3638). Marking the first AI as done!

If you plan to work more on this, I think we should also unify the `compile_fuzzer` function which is copy-pasted in all `build.sh` files now and make it a common script inside base-builder (+ documentation) -- this is the second action item. Updating the docs after that is the third :)

**Comment by inferno-chromium** [comment]
I thought about 2) and 3). i think it will create more confusion for folks when they want to do ideal integration (which we recommend, most projects should have build.sh in their repo). They would have to look this helper script and then integrate it as well. for 2-3 build commands, it feels like a hassle. e.g. https://go.googlesource.com/protobuf/+/d8bc21f7e13fa476be55b17983bd5d43ad8c7121/internal/fuzz/oss-fuzz-build.sh. i prefer to keep it in current way.

**Comment by Dor1s** [comment]
> I thought about 2) and 3). i think it will create more confusion for folks when they want to do ideal integration 

Ah, right, great point!

**Comment by jonathanmetzman** [comment]
I think @catenacyber completed this by adding code coverage support for go.
